// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common/req.proto

package common

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SkuIDReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SkuIDReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SkuIDReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SkuIDReqMultiError, or nil
// if none found.
func (m *SkuIDReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SkuIDReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := SkuIDReqValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SkuIDReqMultiError(errors)
	}

	return nil
}

// SkuIDReqMultiError is an error wrapping multiple validation errors returned
// by SkuIDReq.ValidateAll() if the designated constraints aren't met.
type SkuIDReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SkuIDReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SkuIDReqMultiError) AllErrors() []error { return m }

// SkuIDReqValidationError is the validation error returned by
// SkuIDReq.Validate if the designated constraints aren't met.
type SkuIDReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SkuIDReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SkuIDReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SkuIDReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SkuIDReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SkuIDReqValidationError) ErrorName() string { return "SkuIDReqValidationError" }

// Error satisfies the builtin error interface
func (e SkuIDReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSkuIDReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SkuIDReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SkuIDReqValidationError{}

// Validate checks the field values on PageReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PageReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageReq with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PageReqMultiError, or nil if none found.
func (m *PageReq) ValidateAll() error {
	return m.validate(true)
}

func (m *PageReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	if len(errors) > 0 {
		return PageReqMultiError(errors)
	}

	return nil
}

// PageReqMultiError is an error wrapping multiple validation errors returned
// by PageReq.ValidateAll() if the designated constraints aren't met.
type PageReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageReqMultiError) AllErrors() []error { return m }

// PageReqValidationError is the validation error returned by PageReq.Validate
// if the designated constraints aren't met.
type PageReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageReqValidationError) ErrorName() string { return "PageReqValidationError" }

// Error satisfies the builtin error interface
func (e PageReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageReqValidationError{}
