//*
// 第三方服务,短信，支付

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: core/third-party.proto

package core

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 手机号请求结构
type SendSMSReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"` /// 手机号
}

func (x *SendSMSReq) Reset() {
	*x = SendSMSReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_third_party_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendSMSReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMSReq) ProtoMessage() {}

func (x *SendSMSReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_third_party_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMSReq.ProtoReflect.Descriptor instead.
func (*SendSMSReq) Descriptor() ([]byte, []int) {
	return file_core_third_party_proto_rawDescGZIP(), []int{0}
}

func (x *SendSMSReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// 检测手机验证码合法请求结构
type VCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone int64  `protobuf:"varint,1,opt,name=phone,proto3" json:"phone,omitempty"` /// 手机号
	Code  string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`    /// 验证码
}

func (x *VCodeReq) Reset() {
	*x = VCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_third_party_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VCodeReq) ProtoMessage() {}

func (x *VCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_third_party_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VCodeReq.ProtoReflect.Descriptor instead.
func (*VCodeReq) Descriptor() ([]byte, []int) {
	return file_core_third_party_proto_rawDescGZIP(), []int{1}
}

func (x *VCodeReq) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

func (x *VCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 以太币支付检测请求结构
type ETHPayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          /// 支付合约id
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` /// 支付合约地址
	OrderNo string `protobuf:"bytes,3,opt,name=orderNo,proto3" json:"orderNo,omitempty"` /// 订单号
}

func (x *ETHPayReq) Reset() {
	*x = ETHPayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_third_party_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ETHPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETHPayReq) ProtoMessage() {}

func (x *ETHPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_third_party_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETHPayReq.ProtoReflect.Descriptor instead.
func (*ETHPayReq) Descriptor() ([]byte, []int) {
	return file_core_third_party_proto_rawDescGZIP(), []int{2}
}

func (x *ETHPayReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ETHPayReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ETHPayReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

// 发送短信响应结构
type CodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` /// 验证码
}

func (x *CodeReply) Reset() {
	*x = CodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_third_party_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeReply) ProtoMessage() {}

func (x *CodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_core_third_party_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeReply.ProtoReflect.Descriptor instead.
func (*CodeReply) Descriptor() ([]byte, []int) {
	return file_core_third_party_proto_rawDescGZIP(), []int{3}
}

func (x *CodeReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_core_third_party_proto protoreflect.FileDescriptor

var file_core_third_party_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x2d, 0x70, 0x61, 0x72,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x4d, 0x53, 0x52,
	0x65, 0x71, 0x12, 0x1e, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x72, 0x03, 0x98, 0x01, 0x0b, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x22, 0x47, 0x0a, 0x08, 0x56, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1d,
	0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05,
	0x72, 0x03, 0x98, 0x01, 0x06, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x6a, 0x0a, 0x09, 0x45,
	0x54, 0x48, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x21, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x03, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x03, 0x52, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x22, 0x1f, 0x0a, 0x09, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0xa8, 0x01, 0x0a, 0x0a, 0x54, 0x68, 0x69,
	0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x53,
	0x4d, 0x53, 0x12, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x4d,
	0x53, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x0e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x56, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x36, 0x0a, 0x0b, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x45, 0x54, 0x48, 0x50, 0x61, 0x79, 0x12, 0x0f, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x45, 0x54, 0x48, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x63,
	0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_third_party_proto_rawDescOnce sync.Once
	file_core_third_party_proto_rawDescData = file_core_third_party_proto_rawDesc
)

func file_core_third_party_proto_rawDescGZIP() []byte {
	file_core_third_party_proto_rawDescOnce.Do(func() {
		file_core_third_party_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_third_party_proto_rawDescData)
	})
	return file_core_third_party_proto_rawDescData
}

var file_core_third_party_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_core_third_party_proto_goTypes = []interface{}{
	(*SendSMSReq)(nil),    // 0: core.SendSMSReq
	(*VCodeReq)(nil),      // 1: core.VCodeReq
	(*ETHPayReq)(nil),     // 2: core.ETHPayReq
	(*CodeReply)(nil),     // 3: core.CodeReply
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_core_third_party_proto_depIdxs = []int32{
	0, // 0: core.ThirdParty.SendSMS:input_type -> core.SendSMSReq
	1, // 1: core.ThirdParty.CheckVCode:input_type -> core.VCodeReq
	2, // 2: core.ThirdParty.CheckETHPay:input_type -> core.ETHPayReq
	3, // 3: core.ThirdParty.SendSMS:output_type -> core.CodeReply
	4, // 4: core.ThirdParty.CheckVCode:output_type -> google.protobuf.Empty
	4, // 5: core.ThirdParty.CheckETHPay:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_third_party_proto_init() }
func file_core_third_party_proto_init() {
	if File_core_third_party_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_third_party_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendSMSReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_third_party_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_third_party_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ETHPayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_third_party_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_third_party_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_third_party_proto_goTypes,
		DependencyIndexes: file_core_third_party_proto_depIdxs,
		MessageInfos:      file_core_third_party_proto_msgTypes,
	}.Build()
	File_core_third_party_proto = out.File
	file_core_third_party_proto_rawDesc = nil
	file_core_third_party_proto_goTypes = nil
	file_core_third_party_proto_depIdxs = nil
}
