// 按需全局引入 vant组件
import Vue from 'vue'
import {
  Button,
  Icon,
  Empty,
  List,
  Cell,
  CellGroup,
  Tabbar,
  TabbarItem,
  Search,
  Image,
  Lazyload,
  Swipe,
  SwipeItem,
  Tabs,
  Tab,
  Sticky,
  Divider,
  Form,
  Field,
  Sidebar,
  SidebarItem,
  NavBar,
  SubmitBar,
  PullRefresh,
  GoodsAction,
  GoodsActionIcon,
  GoodsActionButton,
  Popup,
  Sku,
  Overlay,
  Dialog,
  Tag,
  CheckboxGroup,
  Checkbox,
  SwipeCell,
  Stepper,
  Col,
  Row,
  AddressEdit,
  CouponCell,
  CouponList,
  RadioGroup,
  Radio,
  Rate,
  NoticeBar,
  CountDown
} from 'vant'
Vue.use(Button)
  .use(NoticeBar)
  .use(CountDown)
  .use(Rate)
  .use(Radio)
  .use(RadioGroup)
  .use(AddressEdit)
  .use(CouponList)
  .use(CouponCell)
  .use(Col)
  .use(Row)
  .use(Stepper)
  .use(SwipeCell)
  .use(CheckboxGroup)
  .use(Checkbox)
  .use(Tag)
  .use(Dialog)
  .use(Overlay)
  .use(Sku)
  .use(Popup)
  .use(GoodsAction)
  .use(GoodsActionIcon)
  .use(GoodsActionButton)
  .use(PullRefresh)
  .use(Search)
  .use(Image)
  .use(Sticky)
  .use(Form)
  .use(Checkbox)
  .use(Field)
  .use(Sidebar)
  .use(SidebarItem)
  .use(NavBar)
  .use(SubmitBar)
  .use(CellGroup)
Vue.use(Cell).use(Lazyload).use(Swipe)
Vue.use(List).use(Tabs).use(Tab).use(Icon).use(Empty)
Vue.use(Tabbar).use(TabbarItem).use(SwipeItem).use(Divider)
