// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: seckill/seckill.proto

package seckill

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	empty "github.com/golang/protobuf/ptypes/empty"
	proto "google.golang.org/protobuf/proto"
	math "math"
	common "pkg/proto/common"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for seckillService service

func NewSeckillEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for seckillService service

type SeckillService interface {
	// / 秒杀
	Kill(ctx context.Context, in *KillReq, opts ...client.CallOption) (*KillReply, error)
	// / 获取所有秒杀场次
	GetSessionAll(ctx context.Context, in *empty.Empty, opts ...client.CallOption) (*SessionsReply, error)
	// / 获取场次下所有秒杀商品
	GetSessionSkus(ctx context.Context, in *SessionIdReq, opts ...client.CallOption) (*SkusReply, error)
	// / 获取商品秒杀详情
	GetSkuDetail(ctx context.Context, in *common.SkuIDReq, opts ...client.CallOption) (*SkuReply, error)
}

type seckillService struct {
	c    client.Client
	name string
}

func NewSeckillService(name string, c client.Client) SeckillService {
	return &seckillService{
		c:    c,
		name: name,
	}
}

func (c *seckillService) Kill(ctx context.Context, in *KillReq, opts ...client.CallOption) (*KillReply, error) {
	req := c.c.NewRequest(c.name, "seckillService.Kill", in)
	out := new(KillReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillService) GetSessionAll(ctx context.Context, in *empty.Empty, opts ...client.CallOption) (*SessionsReply, error) {
	req := c.c.NewRequest(c.name, "seckillService.GetSessionAll", in)
	out := new(SessionsReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillService) GetSessionSkus(ctx context.Context, in *SessionIdReq, opts ...client.CallOption) (*SkusReply, error) {
	req := c.c.NewRequest(c.name, "seckillService.GetSessionSkus", in)
	out := new(SkusReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillService) GetSkuDetail(ctx context.Context, in *common.SkuIDReq, opts ...client.CallOption) (*SkuReply, error) {
	req := c.c.NewRequest(c.name, "seckillService.GetSkuDetail", in)
	out := new(SkuReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for seckillService service

type SeckillHandler interface {
	// / 秒杀
	Kill(context.Context, *KillReq, *KillReply) error
	// / 获取所有秒杀场次
	GetSessionAll(context.Context, *empty.Empty, *SessionsReply) error
	// / 获取场次下所有秒杀商品
	GetSessionSkus(context.Context, *SessionIdReq, *SkusReply) error
	// / 获取商品秒杀详情
	GetSkuDetail(context.Context, *common.SkuIDReq, *SkuReply) error
}

func RegisterSeckillHandler(s server.Server, hdlr SeckillHandler, opts ...server.HandlerOption) error {
	type seckill interface {
		Kill(ctx context.Context, in *KillReq, out *KillReply) error
		GetSessionAll(ctx context.Context, in *empty.Empty, out *SessionsReply) error
		GetSessionSkus(ctx context.Context, in *SessionIdReq, out *SkusReply) error
		GetSkuDetail(ctx context.Context, in *common.SkuIDReq, out *SkuReply) error
	}
	type Seckill struct {
		seckill
	}
	h := &seckillHandler{hdlr}
	return s.Handle(s.NewHandler(&Seckill{h}, opts...))
}

type seckillHandler struct {
	SeckillHandler
}

func (h *seckillHandler) Kill(ctx context.Context, in *KillReq, out *KillReply) error {
	return h.SeckillHandler.Kill(ctx, in, out)
}

func (h *seckillHandler) GetSessionAll(ctx context.Context, in *empty.Empty, out *SessionsReply) error {
	return h.SeckillHandler.GetSessionAll(ctx, in, out)
}

func (h *seckillHandler) GetSessionSkus(ctx context.Context, in *SessionIdReq, out *SkusReply) error {
	return h.SeckillHandler.GetSessionSkus(ctx, in, out)
}

func (h *seckillHandler) GetSkuDetail(ctx context.Context, in *common.SkuIDReq, out *SkuReply) error {
	return h.SeckillHandler.GetSkuDetail(ctx, in, out)
}
