//*
// 商品秒杀服务

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: seckill/seckill.proto

package seckill

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "pkg/proto/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 秒杀请求结构
type KillReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId     int64  `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`             /// sku id
	AddressId int64  `protobuf:"varint,2,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"` /// 收货地址id
	Num       int64  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`                              /// sku 数量
	Key       string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`                               /// 加密key
}

func (x *KillReq) Reset() {
	*x = KillReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seckill_seckill_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillReq) ProtoMessage() {}

func (x *KillReq) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_seckill_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillReq.ProtoReflect.Descriptor instead.
func (*KillReq) Descriptor() ([]byte, []int) {
	return file_seckill_seckill_proto_rawDescGZIP(), []int{0}
}

func (x *KillReq) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *KillReq) GetAddressId() int64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *KillReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *KillReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 场次id
type SessionIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` /// 场次id
}

func (x *SessionIdReq) Reset() {
	*x = SessionIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seckill_seckill_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionIdReq) ProtoMessage() {}

func (x *SessionIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_seckill_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionIdReq.ProtoReflect.Descriptor instead.
func (*SessionIdReq) Descriptor() ([]byte, []int) {
	return file_seckill_seckill_proto_rawDescGZIP(), []int{1}
}

func (x *SessionIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 秒杀响应结构
type KillReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` /// 订单号
}

func (x *KillReply) Reset() {
	*x = KillReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seckill_seckill_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillReply) ProtoMessage() {}

func (x *KillReply) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_seckill_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillReply.ProtoReflect.Descriptor instead.
func (*KillReply) Descriptor() ([]byte, []int) {
	return file_seckill_seckill_proto_rawDescGZIP(), []int{2}
}

func (x *KillReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// 秒杀场次响应结构
type SessionsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*common.Session `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *SessionsReply) Reset() {
	*x = SessionsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seckill_seckill_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsReply) ProtoMessage() {}

func (x *SessionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_seckill_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsReply.ProtoReflect.Descriptor instead.
func (*SessionsReply) Descriptor() ([]byte, []int) {
	return file_seckill_seckill_proto_rawDescGZIP(), []int{3}
}

func (x *SessionsReply) GetData() []*common.Session {
	if x != nil {
		return x.Data
	}
	return nil
}

// 秒杀商品列表
type SkusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*common.KillSku `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *SkusReply) Reset() {
	*x = SkusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seckill_seckill_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkusReply) ProtoMessage() {}

func (x *SkusReply) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_seckill_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkusReply.ProtoReflect.Descriptor instead.
func (*SkusReply) Descriptor() ([]byte, []int) {
	return file_seckill_seckill_proto_rawDescGZIP(), []int{4}
}

func (x *SkusReply) GetData() []*common.KillSku {
	if x != nil {
		return x.Data
	}
	return nil
}

// 秒杀商品信息
type SkuReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *common.KillSku `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SkuReply) Reset() {
	*x = SkuReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seckill_seckill_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuReply) ProtoMessage() {}

func (x *SkuReply) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_seckill_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuReply.ProtoReflect.Descriptor instead.
func (*SkuReply) Descriptor() ([]byte, []int) {
	return file_seckill_seckill_proto_rawDescGZIP(), []int{5}
}

func (x *SkuReply) GetData() *common.KillSku {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_seckill_seckill_proto protoreflect.FileDescriptor

var file_seckill_seckill_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2f, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x72,
	0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x01, 0x0a, 0x07,
	0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x06, 0x73, 0x6b, 0x75, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00,
	0x52, 0x05, 0x73, 0x6b, 0x75, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x22, 0x02, 0x20, 0x00, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x72, 0x03, 0x98, 0x01,
	0x20, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x27, 0x0a, 0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x1f, 0x0a, 0x09, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x34, 0x0a, 0x0d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x30, 0x0a, 0x09, 0x53, 0x6b, 0x75, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4b, 0x69, 0x6c, 0x6c, 0x53,
	0x6b, 0x75, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x08, 0x53, 0x6b, 0x75, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4b, 0x69, 0x6c, 0x6c,
	0x53, 0x6b, 0x75, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xea, 0x01, 0x0a, 0x07, 0x53, 0x65,
	0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x2c, 0x0a, 0x04, 0x4b, 0x69, 0x6c, 0x6c, 0x12, 0x10, 0x2e,
	0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a,
	0x12, 0x2e, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x3f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x73,
	0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x53, 0x6b, 0x75, 0x73, 0x12, 0x15, 0x2e, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c,
	0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x53, 0x6b, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x33, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x6b, 0x75, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x12, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6b, 0x75, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x53, 0x6b,
	0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x3b, 0x73, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_seckill_seckill_proto_rawDescOnce sync.Once
	file_seckill_seckill_proto_rawDescData = file_seckill_seckill_proto_rawDesc
)

func file_seckill_seckill_proto_rawDescGZIP() []byte {
	file_seckill_seckill_proto_rawDescOnce.Do(func() {
		file_seckill_seckill_proto_rawDescData = protoimpl.X.CompressGZIP(file_seckill_seckill_proto_rawDescData)
	})
	return file_seckill_seckill_proto_rawDescData
}

var file_seckill_seckill_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_seckill_seckill_proto_goTypes = []interface{}{
	(*KillReq)(nil),         // 0: seckill.KillReq
	(*SessionIdReq)(nil),    // 1: seckill.SessionIdReq
	(*KillReply)(nil),       // 2: seckill.KillReply
	(*SessionsReply)(nil),   // 3: seckill.SessionsReply
	(*SkusReply)(nil),       // 4: seckill.SkusReply
	(*SkuReply)(nil),        // 5: seckill.SkuReply
	(*common.Session)(nil),  // 6: common.Session
	(*common.KillSku)(nil),  // 7: common.KillSku
	(*empty.Empty)(nil),     // 8: google.protobuf.Empty
	(*common.SkuIDReq)(nil), // 9: common.SkuIDReq
}
var file_seckill_seckill_proto_depIdxs = []int32{
	6, // 0: seckill.SessionsReply.data:type_name -> common.Session
	7, // 1: seckill.SkusReply.data:type_name -> common.KillSku
	7, // 2: seckill.SkuReply.data:type_name -> common.KillSku
	0, // 3: seckill.seckillService.Kill:input_type -> seckill.KillReq
	8, // 4: seckill.seckillService.GetSessionAll:input_type -> google.protobuf.Empty
	1, // 5: seckill.seckillService.GetSessionSkus:input_type -> seckill.SessionIdReq
	9, // 6: seckill.seckillService.GetSkuDetail:input_type -> common.SkuIDReq
	2, // 7: seckill.seckillService.Kill:output_type -> seckill.KillReply
	3, // 8: seckill.seckillService.GetSessionAll:output_type -> seckill.SessionsReply
	4, // 9: seckill.seckillService.GetSessionSkus:output_type -> seckill.SkusReply
	5, // 10: seckill.seckillService.GetSkuDetail:output_type -> seckill.SkuReply
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_seckill_seckill_proto_init() }
func file_seckill_seckill_proto_init() {
	if File_seckill_seckill_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seckill_seckill_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seckill_seckill_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seckill_seckill_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seckill_seckill_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seckill_seckill_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seckill_seckill_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seckill_seckill_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seckill_seckill_proto_goTypes,
		DependencyIndexes: file_seckill_seckill_proto_depIdxs,
		MessageInfos:      file_seckill_seckill_proto_msgTypes,
	}.Build()
	File_seckill_seckill_proto = out.File
	file_seckill_seckill_proto_rawDesc = nil
	file_seckill_seckill_proto_goTypes = nil
	file_seckill_seckill_proto_depIdxs = nil
}
