global:
  scrape_interval: 15s      # 抓取数据的间隔，默认为1分钟
  evaluation_interval: 15s  # 评估数据的间隔
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  # prometheus 自身数据的抓取配置
  - job_name: prometheus
    static_configs:
      - targets: ["127.0.0.1:9090"]
  - job_name: node_exporter
    scrape_interval: 10s
    static_configs:
      - targets: ["node_exporter:9100"]

  # Go 程序数据的抓取配置
  - job_name: gateway
    metrics_path: /metrics  # 抓取数据的URL路径
    consul_sd_configs:
      - server: consul:8500
        services:
          - gateway
